# Generated by Django 4.2.5 on 2024-09-04 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
