# Generated by Django 4.2.5 on 2024-09-04 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pet_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subcategory',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='pet_category',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='pet_category',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='product_category',
        ),
        migrations.DeleteModel(
            name='PetCategory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductSubcategory',
        ),
    ]
