# Generated by Django 4.2.5 on 2024-09-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecast',
            name='cast_member',
        ),
        migrations.RemoveField(
            model_name='moviecast',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/'),
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='MovieCast',
        ),
    ]
